name: Main build workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.2
      - run: go test -v ./...
